AccessKeyId: 
S3BucketName: 
SecretAccessKey: 
anchor_id: 
backup_path: .
db_host: 192.168.100.250
db_name: postgres
db_password: mysecretpassword
db_port: 5432
db_user: postgres
filename: db_backup
filenamefinal: null
fillenamefinal: 
hash_dump: 
token: 


